name: develop
on: 
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2.0.3
      - name: Build
        run: go build cmd/*.go
  publish:
    name: Publish Snapshot
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: AlejandroAM91/docker-buildx-action@develop
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKER_USERNAME}}/mybookshelf-server
          tags: snapshot
          dockerfile: build/docker/dockerfile
