name: develop
on: 
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2.0.3
      - name: Build
        run: go build cmd/*.go
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Create build image
        run: |
          docker buildx build \
            --target build \
            --platform linux/amd64 \
            --output type=image,push=false \
            --file build/docker/dockerfile \
            --cache-from type=registry,ref=alejandroam91/build-cache:mybookshelf-server \
            --cache-to type=registry,ref=alejandroam91/build-cache:mybookshelf-server,mode=max \
            .
      - name: Create docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --file build/docker/dockerfile \
            --cache-from=alejandroam91/build-cache:mybookshelf-server \
            --cache-from=alejandroam91/mybookshelf-server:snapshot \
            --tag alejandroam91/mybookshelf-server:snapshot \
            .
