name: PRQ
on: pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2.0.3
      - name: Build
        run: go build cmd/*.go
